# Generated by Django 3.1.4 on 2021-01-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputForm',
        ),
    ]
